name             'rails-unicorn-nginx'
maintainer       'Andre Mosin'
maintainer_email 'andre@mosin.com.br'
license          'All rights reserved'
description      'Installs/Configures rails-unicorn-nginx application'
long_description 'Installs/Configures rails-unicorn-nginx application'
version          '0.1.0'

depends 'nginx', '~> 1.8.0'
depends 'apt', '~> 2.3.10'
depends 'rvm', '~> 0.9.2'